# Generated by Django 5.0.2 on 2024-02-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('expires', models.DateTimeField()),
                ('codeType', models.CharField(choices=[('Reg', 'Reg'), ('Inf', 'Inf'), ('Restore', 'Restore'), ('Test', 'Test')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user')),
            ],
        ),
    ]
