# Generated by Django 5.0.2 on 2024-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=254, verbose_name='Password')),
                ('nickname', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
