# Generated by Django 5.0.2 on 2024-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_user_avatar_alter_user_email_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='lastCreated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
