# Generated by Django 5.0.2 on 2024-02-15 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_verificationcode_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='lastCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
