# Generated by Django 5.0.2 on 2024-02-19 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_videotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('pubDT', models.DateField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True, verbose_name='Public')),
                ('proccessed', models.IntegerField(default=0)),
                ('thumbImage', models.ImageField(null=True, upload_to='media/thumbs/%Y/%m/%d/')),
                ('originalVideo', models.FileField(upload_to='media/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('video_240', models.CharField(max_length=1000, null=True)),
                ('video_360', models.CharField(max_length=1000, null=True)),
                ('video_480', models.CharField(max_length=1000, null=True)),
                ('video_720', models.CharField(max_length=1000, null=True)),
                ('video_1080', models.CharField(max_length=1000, null=True)),
                ('video_1440', models.CharField(max_length=1000, null=True)),
                ('video_2160', models.CharField(max_length=1000, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.user')),
            ],
        ),
    ]
