# Generated by Django 5.0.2 on 2024-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pubDT',
            field=models.DateField(null=True),
        ),
    ]
