# Generated by Django 5.0.2 on 2024-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_video_logs_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='logs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
